language: ruby
rvm: 2.4.1

git:
  depth: 6
  lfs_skip_smudge: true

cache:
  bundler: true
  directories:
  - node_modules/
  - lib/
  - vendor/bundle
  - tmp/
  - ".sass-cache"

before_install:
- nvm install 6.10.0

install:
- gem install bundler -v '< 2'
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
- npm install -g bower gulp-cli
- npm install
- bower install
- curl https://s3-eu-west-1.amazonaws.com/wjdp-lib/htmltest > _bin/htmltest
- chmod +x _bin/htmltest
- _bin/htmltest --version

before_script:
- _bin/prep.sh

script:
- gulp build_deploy
- gulp test

after_success:
- _bin/deploy_ghp.sh
